<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BL_SmartAppraisal\BL_SmartAppraisal.csproj" />
    <ProjectReference Include="..\DL_SmartAppraisal\DL_SmartAppraisal.csproj" />
    <ProjectReference Include="..\SmartAppraisal\SmartAppraisal.csproj" />
  </ItemGroup>

</Project>
